version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data:


# version: '3.6'  
# services:  
#   app:
#     build:
#       context: ./app
#     depends_on:
#       - redis
#     environment:
#       - REDIS_HOST=redis
#     ports:
#       - "5000:5000"
#   redis:
#     image: redis:3.2-alpine
#     volumes:
#       - redis_data:/data
# volumes:  
#   redis_data: